#!/usr/bin/env python3
"""Render a self-contained GitHub contribution heatmap SVG."""

from __future__ import annotations

import argparse
import html
import json
import tempfile
from datetime import date
from pathlib import Path


SVG_WIDTH = 860
SVG_HEIGHT = 218
CELL_SIZE = 10
CELL_GAP = 3
GRID_X = 104
GRID_Y = 82
MAX_COLUMNS = 54
PALETTE = ("#21262D", "#0E4429", "#006D32", "#26A641", "#39D353")
MONTH_NAMES = (
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("data/contributions.json"),
        help="Contribution data generated by fetch_contributions.py",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("assets/contrib-heatmap.svg"),
        help="Destination SVG",
    )
    parser.add_argument(
        "--static",
        action="store_true",
        help="Render the final frame without animation",
    )
    return parser.parse_args()


def load_payload(path: Path) -> dict[str, object]:
    with path.open(encoding="utf-8") as handle:
        payload = json.load(handle)

    if payload.get("schema_version") != 1:
        raise RuntimeError("Unsupported contribution data schema")
    days = payload.get("days")
    if not isinstance(days, list) or len(days) < 350:
        raise RuntimeError("Contribution data must contain at least 350 days")

    previous: date | None = None
    for raw_day in days:
        if not isinstance(raw_day, dict):
            raise RuntimeError("Contribution day is not an object")
        parsed_date = date.fromisoformat(str(raw_day["date"]))
        if previous is not None and parsed_date <= previous:
            raise RuntimeError("Contribution days must be unique and sorted")
        previous = parsed_date
        level = int(raw_day["level"])
        count = int(raw_day["count"])
        if level not in range(5) or count < 0:
            raise RuntimeError(f"Invalid contribution value for {parsed_date}")
    return payload


def displayed_days(payload: dict[str, object]) -> tuple[list[dict[str, object]], int]:
    days = list(payload["days"])
    latest_week = max(int(day["week"]) for day in days)
    first_week = max(0, latest_week - (MAX_COLUMNS - 1))
    visible = [day for day in days if int(day["week"]) >= first_week]
    return visible, first_week


def month_labels(days: list[dict[str, object]], first_week: int) -> list[tuple[int, str]]:
    labels: list[tuple[int, str]] = []
    seen: set[tuple[int, int]] = set()
    for day in days:
        parsed = date.fromisoformat(str(day["date"]))
        key = (parsed.year, parsed.month)
        if key in seen:
            continue
        seen.add(key)
        column = int(day["week"]) - first_week
        x = GRID_X + (column * (CELL_SIZE + CELL_GAP))
        if labels and x - labels[-1][0] < 34:
            continue
        labels.append((x, MONTH_NAMES[parsed.month - 1]))
    return labels


def tooltip_text(day: dict[str, object]) -> str:
    parsed = date.fromisoformat(str(day["date"]))
    count = int(day["count"])
    noun = "contribution" if count == 1 else "contributions"
    return f"{count} {noun} on {MONTH_NAMES[parsed.month - 1]} {parsed.day}, {parsed.year}"


def render_svg(payload: dict[str, object], static: bool) -> str:
    days, first_week = displayed_days(payload)
    stats = payload["stats"]
    username = html.escape(str(payload["username"]))
    cells: list[str] = []
    for day in days:
        column = int(day["week"]) - first_week
        row = int(day["weekday"])
        x = GRID_X + (column * (CELL_SIZE + CELL_GAP))
        y = GRID_Y + (row * (CELL_SIZE + CELL_GAP))
        level = int(day["level"])
        animation = "animation: none;" if static else f"animation-delay: {0.08 + column * 0.018 + row * 0.024:.3f}s;"
        cells.append(
            f'<rect class="day level-{level}" x="{x}" y="{y}" '
            f'width="{CELL_SIZE}" height="{CELL_SIZE}" rx="2" style="{animation}">'
            f'<title>{html.escape(tooltip_text(day))}</title></rect>'
        )

    labels = "".join(
        f'<text class="axis" x="{x}" y="70">{label}</text>'
        for x, label in month_labels(days, first_week)
        if x <= SVG_WIDTH - 34
    )
    footer = (
        f'{int(stats["total"]):,} contributions  |  '
        f'{int(stats["active_days"])} active days  |  '
        f'{int(stats["longest_streak"])}-day longest streak'
    )

    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="{SVG_WIDTH}" height="{SVG_HEIGHT}" viewBox="0 0 {SVG_WIDTH} {SVG_HEIGHT}" role="img" aria-labelledby="heatmap-title heatmap-desc">
  <title id="heatmap-title">{username} GitHub contribution graph</title>
  <desc id="heatmap-desc">A daily contribution calendar sourced directly from GitHub and refreshed every day.</desc>
  <style>
    .terminal-text {{ fill: #8B949E; font: 12px 'Cascadia Mono', 'SFMono-Regular', Consolas, 'Liberation Mono', monospace; }}
    .axis {{ fill: #8B949E; font: 10px 'Cascadia Mono', 'SFMono-Regular', Consolas, 'Liberation Mono', monospace; }}
    .summary {{ fill: #C9D1D9; font: 11px 'Cascadia Mono', 'SFMono-Regular', Consolas, 'Liberation Mono', monospace; }}
    .day {{ transform-box: fill-box; transform-origin: center; animation: cell-enter 0.42s cubic-bezier(.2,.8,.2,1) both; }}
    .level-0 {{ fill: {PALETTE[0]}; }}
    .level-1 {{ fill: {PALETTE[1]}; }}
    .level-2 {{ fill: {PALETTE[2]}; }}
    .level-3 {{ fill: {PALETTE[3]}; }}
    .level-4 {{ fill: {PALETTE[4]}; }}
    @keyframes cell-enter {{ from {{ opacity: 0; transform: scale(0.2); }} to {{ opacity: 1; transform: scale(1); }} }}
    @media (prefers-reduced-motion: reduce) {{ .day {{ animation: none !important; }} }}
  </style>
  <rect x="1" y="1" width="858" height="216" rx="8" fill="#0D1117" stroke="#30363D" stroke-width="2" />
  <path d="M1 45 H859" stroke="#30363D" />
  <circle cx="22" cy="23" r="6" fill="#FF7B72" />
  <circle cx="42" cy="23" r="6" fill="#F2CC60" />
  <circle cx="62" cy="23" r="6" fill="#3FB950" />
  <text class="terminal-text" x="282" y="28">ibam@github: ~ $ ./contributions.sh --year</text>
  {labels}
  <text class="axis" x="70" y="103">Mon</text>
  <text class="axis" x="70" y="129">Wed</text>
  <text class="axis" x="70" y="155">Fri</text>
  {''.join(cells)}
  <text class="summary" x="104" y="202">{html.escape(footer)}</text>
</svg>
'''


def write_atomic(output: Path, rendered: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        newline="\n",
        dir=output.parent,
        delete=False,
    ) as handle:
        handle.write(rendered)
        temporary = Path(handle.name)
    temporary.replace(output)


def main() -> None:
    args = parse_args()
    payload = load_payload(args.input)
    write_atomic(args.output, render_svg(payload, args.static))
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
