#!/usr/bin/env python3
"""Render GitHub's official contribution cells with native geometry."""

from __future__ import annotations

import argparse
import html
import json
import tempfile
from datetime import date
from pathlib import Path


SVG_WIDTH = 860
SVG_HEIGHT = 158
CELL_SIZE = 11
CELL_GAP = 4
CELL_STEP = CELL_SIZE + CELL_GAP
GRID_LEFT = 51
GRID_TOP = 27
WEEK_COLUMNS = 53
DARK_PALETTE = ("#151B23", "#033A16", "#196C2E", "#2EA043", "#56D364")
LIGHT_PALETTE = ("#EBEDF0", "#9BE9A8", "#40C463", "#30A14E", "#216E39")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("data/contributions.json"),
        help="Official contribution data generated by fetch_contributions.py",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("assets/contrib-heatmap.svg"),
        help="Destination SVG",
    )
    parser.add_argument(
        "--static",
        action="store_true",
        help="Render the final frame without animation",
    )
    return parser.parse_args()


def load_payload(path: Path) -> dict[str, object]:
    with path.open(encoding="utf-8") as handle:
        payload = json.load(handle)
    if payload.get("schema_version") != 2:
        raise RuntimeError("Unsupported contribution data schema")

    days = payload.get("days")
    months = payload.get("months")
    if not isinstance(days, list) or not 350 <= len(days) <= 371:
        raise RuntimeError("Contribution data must contain 350-371 official dates")
    if not isinstance(months, list) or len(months) != 13:
        raise RuntimeError("Contribution data must contain 13 official month labels")
    if sum(int(month["span"]) for month in months) != WEEK_COLUMNS:
        raise RuntimeError("Official month headers must span exactly 53 weeks")

    previous: date | None = None
    coordinates: set[tuple[int, int]] = set()
    for raw_day in days:
        parsed_date = date.fromisoformat(str(raw_day["date"]))
        if previous is not None and (parsed_date - previous).days != 1:
            raise RuntimeError("Contribution dates must be consecutive and sorted")
        previous = parsed_date
        level = int(raw_day["level"])
        count = int(raw_day["count"])
        week = int(raw_day["week"])
        weekday = int(raw_day["weekday"])
        if level not in range(5) or count < 0:
            raise RuntimeError(f"Invalid official value for {parsed_date}")
        if week not in range(WEEK_COLUMNS) or weekday not in range(7):
            raise RuntimeError(f"Invalid official coordinate for {parsed_date}")
        coordinate = (week, weekday)
        if coordinate in coordinates:
            raise RuntimeError(f"Duplicate official coordinate for {parsed_date}")
        coordinates.add(coordinate)
        if not str(raw_day.get("tooltip", "")).strip():
            raise RuntimeError(f"Missing official tooltip for {parsed_date}")

    total = sum(int(day["count"]) for day in days)
    if total != int(payload.get("total_contributions", -1)):
        raise RuntimeError("Official total does not match the tooltip-derived sum")
    return payload


def render_svg(payload: dict[str, object], static: bool) -> str:
    cells: list[str] = []
    for day in payload["days"]:
        week = int(day["week"])
        weekday = int(day["weekday"])
        level = int(day["level"])
        x = GRID_LEFT + week * CELL_STEP
        y = GRID_TOP + weekday * CELL_STEP
        delay = 0 if static else 0.06 + week * 0.026 + weekday * 0.04
        style = (
            "animation:none;opacity:1;transform:none"
            if static
            else f"animation-delay:{delay:.3f}s"
        )
        cells.append(
            f'<rect class="day level-{level}" x="{x}" y="{y}" '
            f'width="{CELL_SIZE}" height="{CELL_SIZE}" rx="2" '
            f'shape-rendering="geometricPrecision" style="{style}">'
            f'<title>{html.escape(str(day["tooltip"]))}</title></rect>'
        )

    month_labels = "".join(
        f'<text class="axis" x="{GRID_LEFT + int(month["start_week"]) * CELL_STEP}" '
        f'y="15">{html.escape(str(month["label"]))}</text>'
        for month in payload["months"]
    )
    total = int(payload["total_contributions"])
    legend_x = 714
    legend: list[str] = [
        f'<text class="axis" x="{legend_x}" y="150">Less</text>'
    ]
    swatch_x = legend_x + 28
    for level in range(5):
        legend.append(
            f'<rect class="legend-cell level-{level}" x="{swatch_x}" y="140" '
            f'width="10" height="10" rx="3" />'
        )
        swatch_x += 14
    legend.append(f'<text class="axis" x="{swatch_x + 2}" y="150">More</text>')

    dark_rules = "\n".join(
        f"    .level-{index} {{ fill: {color}; }}"
        for index, color in enumerate(DARK_PALETTE)
    )
    light_rules = "\n".join(
        f"      .level-{index} {{ fill: {color}; }}"
        for index, color in enumerate(LIGHT_PALETTE)
    )
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="{SVG_WIDTH}" height="{SVG_HEIGHT}" viewBox="0 0 {SVG_WIDTH} {SVG_HEIGHT}" role="img" aria-labelledby="heatmap-title heatmap-desc" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace">
  <title id="heatmap-title">{html.escape(str(payload["username"]))} GitHub contribution graph</title>
  <desc id="heatmap-desc">{total:,} official GitHub contributions from {payload["range"]["from"]} through {payload["range"]["to"]}.</desc>
  <style>
    .axis {{ fill: #7D8590; font-size: 10px; }}
    .summary {{ fill: #E6EDF3; font-size: 12px; font-weight: 700; }}
    .day {{
      opacity: 0;
      transform-box: fill-box;
      transform-origin: center;
      animation: contribution-enter 0.40s cubic-bezier(.2,.8,.2,1) both;
      stroke: #010409;
      stroke-opacity: 0.05;
      stroke-width: 0.8;
    }}
    .legend-cell {{
      stroke: #010409;
      stroke-opacity: 0.05;
      stroke-width: 0.8;
    }}
{dark_rules}
    @keyframes contribution-enter {{
      from {{ opacity: 0; transform: translateY(-5px) scale(0.72); }}
      to {{ opacity: 1; transform: translateY(0) scale(1); }}
    }}
    @media (prefers-color-scheme: light) {{
      .axis {{ fill: #57606A; }}
      .summary {{ fill: #1F2328; }}
      .day, .legend-cell {{ stroke: #1F2328; stroke-opacity: 0.15; }}
{light_rules}
    }}
    @media (prefers-reduced-motion: reduce) {{
      .day {{ animation: none !important; opacity: 1; transform: none; }}
    }}
  </style>
  {month_labels}
  <text class="axis" x="14" y="51">Mon</text>
  <text class="axis" x="14" y="81">Wed</text>
  <text class="axis" x="14" y="111">Fri</text>
  {''.join(cells)}
  <text class="summary" x="{GRID_LEFT}" y="151">{total:,} contributions in the last year</text>
  {''.join(legend)}
</svg>
'''


def write_atomic(output: Path, rendered: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        newline="\n",
        dir=output.parent,
        delete=False,
    ) as handle:
        handle.write(rendered)
        temporary = Path(handle.name)
    temporary.replace(output)


def main() -> None:
    args = parse_args()
    payload = load_payload(args.input)
    write_atomic(args.output, render_svg(payload, args.static))
    print(
        f"Wrote {args.output}: {len(payload['days'])} cells, "
        f"{payload['total_contributions']} contributions"
    )


if __name__ == "__main__":
    main()
